apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-multi-requests
spec:
  template:
    spec:
      containers:
        - image: hong0331/knative-serving-wasm-multi-requests  #CONFIGURE ME: Change the image name
          ports:
            - containerPort: 8080

    